Comenzamos importando pandas para poder obtener los datos de nuestro csv.

In [45]:
import pandas as pd;
datos_bancarios = pd.read_csv('bank-additional.csv', index_col = 0)
datos_bancarios.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

Renombramos la columna de "_id" a "ID" para poder ejecutar el merge de manera directa on "ID".

In [ ]:
rename_ID = datos_bancarios["id_"]
datos_bancarios.drop("id_",axis = 1,inplace = True)
datos_bancarios['ID'] = rename_ID

In [10]:
datos_bancarios["ID"].head(3)

0    089b39d8-e4d0-461b-87d4-814d71e0e079
1    e9d37224-cb6f-4942-98d7-46672963d097
2    3f9f49b5-e410-4948-bf6e-f9244f04918b
Name: ID, dtype: object

Importamos los datos de nuestro xlsx.

In [11]:
datos_clientes_2012 = pd.read_excel(
    'customer-details.xlsx',
    sheet_name='2012',    
    index_col=0,          
    header=0,
    engine='openpyxl'  # Para archivos .xlsx
)
datos_clientes_2012.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

Realizamos, ahora sí, el merge para contar con nuestros datos centralizados.

In [16]:
bank_data = datos_bancarios.merge(datos_clientes_2012, how= 'inner', on='ID')
bank_data.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,y,date,latitude,longitude,ID,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,...,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,161770,1,0,2012-04-04,29
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,...,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,85477,1,1,2012-12-30,7
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,...,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,147233,1,1,2012-02-02,5
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,...,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,121393,1,2,2012-12-21,29
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,...,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,63164,1,2,2012-06-20,20

Para realizar el formateo de la columna 'Income' tendremos que obtener la serie, asegurarnos de que el type es correcto (float) y ayudarnos del .map para aplicar el formateo deseado.

En este caso el formateo consta de un separador de miles, dos decimales y con 'f' nos aseguramos de que sea legible como formato float.

In [46]:
bank_data['Income'] = bank_data['Income'].astype(float)
bank_data['Formated_Income'] = bank_data['Income'].map('{:,.2f}€'.format)
bank_data.drop('Income', axis=1, inplace=True) #Aquí estamos eliminando la columna antigua de 'Income'
bank_data.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,ID,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,Formated_Income
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079,1,0,2012-04-04,29,"161,770.00€"
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097,1,1,2012-12-30,7,"85,477.00€"
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b,1,1,2012-02-02,5,"147,233.00€"
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e,1,2,2012-12-21,29,"121,393.00€"
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,1,2,2012-06-20,20,"63,164.00€"