Comenzamos importando pandas para poder obtener los datos de nuestro csv.

In [40]:
# Importaciones necesarias para correr el notebook correctamente
import pandas as pd;
import numpy as np 

pd.set_option('display.max_columns', None) #Modificamos el stting default de pandas para poder ver todas las columnas

datos_bancarios = pd.read_csv('../raw_data/bank-additional.csv', index_col = 0)
datos_bancarios.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

Renombramos la columna de "_id" a "ID" para poder ejecutar el merge de manera directa on "ID".

In [41]:
rename_ID = datos_bancarios["id_"]
datos_bancarios.drop("id_",axis = 1,inplace = True)
datos_bancarios['ID'] = rename_ID

In [42]:
datos_bancarios["ID"].head(3)

0    089b39d8-e4d0-461b-87d4-814d71e0e079
1    e9d37224-cb6f-4942-98d7-46672963d097
2    3f9f49b5-e410-4948-bf6e-f9244f04918b
Name: ID, dtype: object

Importamos los datos de nuestro xlsx.

In [43]:
datos_clientes_2012 = pd.read_excel(
    '../raw_data/customer-details.xlsx',
    sheet_name='2012',    
    index_col=0,          
    header=0,
    engine='openpyxl'
)
print('Clientes 2012')
datos_clientes_2012.head()

Clientes 2012

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [44]:
datos_clientes_2013 = pd.read_excel(
    '../raw_data/customer-details.xlsx',
    sheet_name='2013',    
    index_col=0,          
    header=0,
    engine='openpyxl'
)
print('Clientes 2013')
datos_clientes_2013.head()

Clientes 2013

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,82407,0,1,2013-10-07,29,ef81336c-e41a-46d0-8a30-5d4ac3b836be
1,24877,0,0,2013-04-21,32,50b224ac-84b4-42a7-aba9-3e1d1d620479
2,78839,1,0,2013-11-25,21,9cb15c53-b647-464a-add9-09cdae04897c
3,113859,1,1,2013-01-06,12,f8aaf334-949d-4943-a214-b64fe9c088b4
4,147317,0,0,2013-07-10,14,885fe85a-3718-4760-a32a-a57628cf7528

In [45]:
datos_clientes_2014 = pd.read_excel(
    '../raw_data/customer-details.xlsx',
    sheet_name='2014',    
    index_col=0,          
    header=0,
    engine='openpyxl'
)
print('Clientes 2014')
datos_clientes_2014.head()

Clientes 2014

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,168812,1,1,2014-06-10,27,4d6c811c-0f24-4a73-b374-2ebd1f80d46e
1,108615,2,1,2014-04-05,24,eef0f24f-cbdb-4c67-b371-09d7bc59695e
2,179041,0,2,2014-09-22,4,bbfdcedd-199d-4927-94bb-5dad051ff471
3,116639,2,2,2014-08-16,3,e8ebb67d-4ee1-4615-b701-eefe3af607eb
4,49537,0,1,2014-09-05,28,f7f79ace-0024-4505-a401-f340946f0942

Realizamos, ahora sí, el merge para contar con nuestros datos centralizados.

In [46]:
bank_data = datos_bancarios.merge(datos_clientes_2012, how= 'inner', on='ID')
bank_data = datos_bancarios.merge(datos_clientes_2013, how= 'inner', on='ID')
bank_data = datos_bancarios.merge(datos_clientes_2014, how= 'inner', on='ID')

print(f'Número total de duplicados: {bank_data['ID'].duplicated().sum()}')
bank_data.head()

Número total de duplicados: 0

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,ID,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
0,36.0,admin.,SINGLE,high.school,0.0,1.0,0.0,telephone,777,2,999,0,NONEXISTENT,-1.8,"93,075","-47,1",NaN,"5099,1",no,3-junio-2019,37.506,-118.282,4d6c811c-0f24-4a73-b374-2ebd1f80d46e,168812,1,1,2014-06-10,27
1,39.0,admin.,MARRIED,university.degree,0.0,1.0,0.0,cellular,161,1,999,1,FAILURE,-1.8,"93,075","-47,1","1,405","5099,1",no,10-julio-2017,45.703,-90.123,eef0f24f-cbdb-4c67-b371-09d7bc59695e,108615,2,1,2014-04-05,24
2,NaN,admin.,DIVORCED,high.school,0.0,1.0,0.0,cellular,117,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,8-septiembre-2018,46.564,-84.218,bbfdcedd-199d-4927-94bb-5dad051ff471,179041,0,2,2014-09-22,4
3,50.0,management,MARRIED,basic.9y,0.0,1.0,0.0,cellular,329,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,23-julio-2015,43.766,-108.455,e8ebb67d-4ee1-4615-b701-eefe3af607eb,116639,2,2,2014-08-16,3
4,55.0,admin.,MARRIED,basic.4y,0.0,0.0,0.0,cellular,155,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,18-mayo-2019,31.184,-97.182,f7f79ace-0024-4505-a401-f340946f0942,49537,0,1,2014-09-05,28

Para realizar el formateo de la columna 'Income' tendremos que obtener la serie, asegurarnos de que el type es correcto (float) y ayudarnos del .map para aplicar el formateo deseado.

En este caso el formateo consta de un separador de miles, dos decimales y con 'f' nos aseguramos de que sea legible como formato float.

In [47]:
bank_data['Income'] = bank_data['Income'].astype(float)
bank_data['Formated_Income'] = bank_data['Income'].map('{:,.2f}€'.format)
bank_data.drop('Income', axis=1, inplace=True) #Aquí estamos eliminando la columna antigua de 'Income'
bank_data.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,ID,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,Formated_Income
0,36.0,admin.,SINGLE,high.school,0.0,1.0,0.0,telephone,777,2,999,0,NONEXISTENT,-1.8,"93,075","-47,1",NaN,"5099,1",no,3-junio-2019,37.506,-118.282,4d6c811c-0f24-4a73-b374-2ebd1f80d46e,1,1,2014-06-10,27,"168,812.00€"
1,39.0,admin.,MARRIED,university.degree,0.0,1.0,0.0,cellular,161,1,999,1,FAILURE,-1.8,"93,075","-47,1","1,405","5099,1",no,10-julio-2017,45.703,-90.123,eef0f24f-cbdb-4c67-b371-09d7bc59695e,2,1,2014-04-05,24,"108,615.00€"
2,NaN,admin.,DIVORCED,high.school,0.0,1.0,0.0,cellular,117,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,8-septiembre-2018,46.564,-84.218,bbfdcedd-199d-4927-94bb-5dad051ff471,0,2,2014-09-22,4,"179,041.00€"
3,50.0,management,MARRIED,basic.9y,0.0,1.0,0.0,cellular,329,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,23-julio-2015,43.766,-108.455,e8ebb67d-4ee1-4615-b701-eefe3af607eb,2,2,2014-08-16,3,"116,639.00€"
4,55.0,admin.,MARRIED,basic.4y,0.0,0.0,0.0,cellular,155,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,18-mayo-2019,31.184,-97.182,f7f79ace-0024-4505-a401-f340946f0942,0,1,2014-09-05,28,"49,537.00€"

Si nos fijamos en los datos podemos ver como tenemos dos columnas de fechas con formatos distintos, la más llamativa es la columna 'date' asi que vamos a asemejar ambas.                   
Para ello vamos a hacer lo siguiente:

Con el método isnull() controlamos los posibles null que nos encontremos.

In [48]:
meses = { # Creamos un diccionario con los nombres de los meses y su correspondiente valor numérico
        'enero': '01', 'febrero': '02', 'marzo': '03', 'abril': '04',
        'mayo': '05', 'junio': '06', 'julio': '07', 'agosto': '08',
        'septiembre': '09', 'octubre': '10', 'noviembre': '11', 'diciembre': '12'
}

def format_date(date):
    if pd.isnull(date):
        return None
    
    parts = date.split('-') #Separamos la fecha por los '-' para obtener las tres partes de la misma
    return parts[2] + '-' +  meses.get(parts[1]) + '-' + parts[0] # reformamos la fecha como a nosotros nos interesa YY/MM/DD

bank_data['date'] = bank_data['date'].apply(format_date)

bank_data.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,ID,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,Formated_Income
0,36.0,admin.,SINGLE,high.school,0.0,1.0,0.0,telephone,777,2,999,0,NONEXISTENT,-1.8,"93,075","-47,1",NaN,"5099,1",no,2019-06-3,37.506,-118.282,4d6c811c-0f24-4a73-b374-2ebd1f80d46e,1,1,2014-06-10,27,"168,812.00€"
1,39.0,admin.,MARRIED,university.degree,0.0,1.0,0.0,cellular,161,1,999,1,FAILURE,-1.8,"93,075","-47,1","1,405","5099,1",no,2017-07-10,45.703,-90.123,eef0f24f-cbdb-4c67-b371-09d7bc59695e,2,1,2014-04-05,24,"108,615.00€"
2,NaN,admin.,DIVORCED,high.school,0.0,1.0,0.0,cellular,117,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,2018-09-8,46.564,-84.218,bbfdcedd-199d-4927-94bb-5dad051ff471,0,2,2014-09-22,4,"179,041.00€"
3,50.0,management,MARRIED,basic.9y,0.0,1.0,0.0,cellular,329,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,2015-07-23,43.766,-108.455,e8ebb67d-4ee1-4615-b701-eefe3af607eb,2,2,2014-08-16,3,"116,639.00€"
4,55.0,admin.,MARRIED,basic.4y,0.0,0.0,0.0,cellular,155,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,2019-05-18,31.184,-97.182,f7f79ace-0024-4505-a401-f340946f0942,0,1,2014-09-05,28,"49,537.00€"

Ahora vamos a tratar la columna job, para asegurarnos de que los null se transformen en 'Unemployed'.                                               
Haremos algo similar a lo previamente realizado con la culumna 'date'.

In [49]:
def isUnemployed(job: str):
    if pd.isnull(job):
        return 'Unemployed'
    else:
        return job
    
bank_data['job'] = bank_data['job'].apply(isUnemployed)
no_job = bank_data['job'] == 'Unemployed'

unemployed_people = bank_data[no_job].size

Gracias a este filtrado de datos ahora sabemos la cantidad de clientes que están desempleados, nos servirá en el futuro.

Vamos a comprobar ahora, de la misma manera, los clientes que no cuentan con estudios.

In [50]:
def noStudies(education):
    if pd.isnull(education):
        return 'No studies'
    else: 
        return education

bank_data['education'] = bank_data['education'].apply(noStudies)
no_education = bank_data['education'] == 'No studies'
noEducation_people = bank_data[no_education].size #Aplicamos el filtrado

noEducation_people

16940

Si nos fijamos en la columna de age, las edades están en float, vamos a solucionarlo.

In [51]:
bank_data['age'].head(3)

0    36.0
1    39.0
2     NaN
Name: age, dtype: float64

In [52]:

def fillNulls(age): #Limpiamos los nulos primero
    if pd.isnull(age):
        return 0
    else: 
        return age

bank_data['age'] = bank_data['age'].apply(fillNulls)
bank_data['age'] = bank_data['age'].astype(int)
bank_data['age'].head(3)

0    36
1    39
2     0
Name: age, dtype: int64

Sin embargo, no es lo más óptimo para el análisis dejar esos ceros ahí, por ello vamos a intercambiar esos ceros por la media de la edad, apra hacerle un poco de justicia al análisis

In [53]:
media_edad = np.mean(bank_data['age']).astype(int)
print(f'Teniendo en cuenta que la media de edad es de {media_edad} años, vamos a realizar la sustitución')

def setAgeMean(age): 
    if age == 0:
        return media_edad
    else: 
        return age
    
bank_data['age'] = bank_data['age'].apply(setAgeMean)
bank_data['age'].head()

Teniendo en cuenta que la media de edad es de 34 años, vamos a realizar la sustitución

0    36
1    39
2    34
3    50
4    55
Name: age, dtype: int64

Fijándonos un poco podemos darnos cuenta de que las columnas 'default', 'housing' y 'loan' son columnas booleanas, asi que vamos a formatearlas usando un mismo método y cambiando los valores por 'Yes' y 'No' para facilitar la legibilidad.

In [54]:
# Vamos a usar el método fillNulls para limpiar las columnas y los pasamos a str para poder hacer la sustitución
bank_data['default'] = bank_data['default'].apply(fillNulls).astype(str)
bank_data['housing'] = bank_data['housing'].apply(fillNulls).astype(str)
bank_data['loan'] = bank_data['loan'].apply(fillNulls).astype(str)

def yesNoColumn(booleanValue):
    if booleanValue == '0':
        return 'No'
    else:
        return 'Yes'

#Ahora vamos a sustituir los valores actuales por los deseados
bank_data['default'] = bank_data['default'].apply(yesNoColumn)
bank_data['housing'] = bank_data['housing'].apply(yesNoColumn)
bank_data['loan'] = bank_data['loan'].apply(yesNoColumn)

bank_data.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,ID,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,Formated_Income
0,36,admin.,SINGLE,high.school,Yes,Yes,Yes,telephone,777,2,999,0,NONEXISTENT,-1.8,"93,075","-47,1",NaN,"5099,1",no,2019-06-3,37.506,-118.282,4d6c811c-0f24-4a73-b374-2ebd1f80d46e,1,1,2014-06-10,27,"168,812.00€"
1,39,admin.,MARRIED,university.degree,Yes,Yes,Yes,cellular,161,1,999,1,FAILURE,-1.8,"93,075","-47,1","1,405","5099,1",no,2017-07-10,45.703,-90.123,eef0f24f-cbdb-4c67-b371-09d7bc59695e,2,1,2014-04-05,24,"108,615.00€"
2,34,admin.,DIVORCED,high.school,Yes,Yes,Yes,cellular,117,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,2018-09-8,46.564,-84.218,bbfdcedd-199d-4927-94bb-5dad051ff471,0,2,2014-09-22,4,"179,041.00€"
3,50,management,MARRIED,basic.9y,Yes,Yes,Yes,cellular,329,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,2015-07-23,43.766,-108.455,e8ebb67d-4ee1-4615-b701-eefe3af607eb,2,2,2014-08-16,3,"116,639.00€"
4,55,admin.,MARRIED,basic.4y,Yes,Yes,Yes,cellular,155,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,2019-05-18,31.184,-97.182,f7f79ace-0024-4505-a401-f340946f0942,0,1,2014-09-05,28,"49,537.00€"

In [55]:
bank_data['education'].value_counts()

education
university.degree      4354
high.school            3447
basic.9y               1951
professional.course    1681
basic.4y               1301
basic.6y                721
No studies              605
illiterate                4
Name: count, dtype: int64